language: php

# We do Behat testing here, lots of sudo going on
sudo: required

# run tests on php 7.0 only and let unit / integration tests deal with php differences
php:
  - 7.0

# Use latests Firefox version to match what we support and faster execution
addons:
  firefox: "latest"

# list of paths/bundle to execute
env:
  - INSTALL="demoContentNonUniqueDB" PROFILE="demo" TEST="content"
  - PROFILE="demo" TEST="clean"
  - PROFILE="rest" TEST="fullJson"
  - PROFILE="rest" TEST="fullXml"
  - PROFILE="platformui" TEST="standard"


# test only master (+ Pull requests)
branches:
  only:
    - master

# install packages
before_install:
  - ./bin/.travis/prepare_system.sh
  - ./bin/.travis/prepare_selenium2.sh

# setup requirements for running tests
before_script:
  # Prepare eZ Publish (composer, permissions, assets, cache warmup)
  - ./bin/.travis/prepare_ezpublish.sh

# execute behat as the script command
script:
  - php bin/behat -vc behat.yml.dist --profile $PROFILE --suite $TEST

# disable mail notifications
notifications:
  email: false

# reduce depth (history) of git checkout
git:
  depth: 30
